//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        internal static string AccManaCenter {
            get {
                return ResourceManager.GetString("AccManaCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. 3-11, Wenhua Road, Heping District, Shenyang, P. R. China.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Document.
        /// </summary>
        internal static string APIDoc {
            get {
                return ResourceManager.GetString("APIDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        internal static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Obisoft Account.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required..
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make ideas real.
        /// </summary>
        internal static string HomeSubTitle {
            get {
                return ResourceManager.GetString("HomeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Greate Things.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email address!.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        internal static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep our pride.
        /// </summary>
        internal static string Keepourpride {
            get {
                return ResourceManager.GetString("Keepourpride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        internal static string Licensing {
            get {
                return ResourceManager.GetString("Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My TanZone.
        /// </summary>
        internal static string MyTanZone {
            get {
                return ResourceManager.GetString("MyTanZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obisoft Account (Email).
        /// </summary>
        internal static string ObisoftAccount {
            get {
                return ResourceManager.GetString("ObisoftAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        internal static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        internal static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter if you are a student or enterprise, if you are in U.S. or not, there must exists something you need..
        /// </summary>
        internal static string PortSub {
            get {
                return ResourceManager.GetString("PortSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user..
        /// </summary>
        internal static string RegisterasaNewUser {
            get {
                return ResourceManager.GetString("RegisterasaNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not require technology. With only an idea, we will bring it to billions of devices to run as a real application. One click, one dream, win thousands of users..
        /// </summary>
        internal static string Ser1SubTi {
            get {
                return ResourceManager.GetString("Ser1SubTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develope for idea.
        /// </summary>
        internal static string Ser1Ti {
            get {
                return ResourceManager.GetString("Ser1Ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own culture. Do not need lots of money. No matter 2D or 3D, no matter pic or video, everything and be more beautiful. Every application can be more cool.
        /// </summary>
        internal static string Ser2SubTi {
            get {
                return ResourceManager.GetString("Ser2SubTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Design.
        /// </summary>
        internal static string Ser2Ti {
            get {
                return ResourceManager.GetString("Ser2Ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any time, any place, and you won&apos;t run into technical problems. WeBo, WeChat, voting, statistics, information, management ... ... Our technical support you forever. Remember: technology is not an issue with us..
        /// </summary>
        internal static string Ser3SubTi {
            get {
                return ResourceManager.GetString("Ser3SubTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Support.
        /// </summary>
        internal static string Ser3Ti {
            get {
                return ResourceManager.GetString("Ser3Ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether start-up businesses need a Web site, or an established company for scientific research, we will be your technical team. In this mobile first cloud first age, we want to bring you technical strength..
        /// </summary>
        internal static string Ser4SubTi {
            get {
                return ResourceManager.GetString("Ser4SubTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For enterprises.
        /// </summary>
        internal static string Ser4Ti {
            get {
                return ResourceManager.GetString("Ser4Ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter websites, or mobile applications, or other services like wechat, we only need your thoughts..
        /// </summary>
        internal static string SerSubTi {
            get {
                return ResourceManager.GetString("SerSubTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceCode.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath with reliable service..
        /// </summary>
        internal static string Sta1Ani1 {
            get {
                return ResourceManager.GetString("Sta1Ani1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in your Obisoft account to enjoy personal service..
        /// </summary>
        internal static string Sta1Ani2 {
            get {
                return ResourceManager.GetString("Sta1Ani2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TanZone.
        /// </summary>
        internal static string TanZone {
            get {
                return ResourceManager.GetString("TanZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Log in?.
        /// </summary>
        internal static string UnabletoLogin {
            get {
                return ResourceManager.GetString("UnabletoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Obsoft account to log in..
        /// </summary>
        internal static string UserSerToLog {
            get {
                return ResourceManager.GetString("UserSerToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t a rapid path for us startups, but it&apos;s better to create masterpieces. Our team have only created less than 10 products in the first year after establishment, obviously, that’s too few. However, there isn’t so strong relationship between us tech-teams and time, since the young is always looking forward to the advanced. Of course there is technology in our blood, not only for the outsources, but also the ability of facing the Internet. Hardly would we share our products with you when it’s finished [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VF1Parg {
            get {
                return ResourceManager.GetString("VF1Parg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although only for the technology, our team is filled with love, belief, and attitude. So we’d like to be in this way, enjoy it, and keep going like it forever. Competing with the advanced technology in this world, we’ll respect them firstly and they’ll push us forward then. We’ll keep what we cherish, what we take pride in, so, we’re always willing to follow our heart. Focus on the tech, at least, it deserves the time we spend. For other things, just to be judged by the users..
        /// </summary>
        internal static string VF2Parg {
            get {
                return ResourceManager.GetString("VF2Parg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What We do.
        /// </summary>
        internal static string WhatWeDo {
            get {
                return ResourceManager.GetString("WhatWeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect to the technology today gives us the chance to face the Internet today. No matter web application, native app or enterprise solution, maybe you can find something new here..
        /// </summary>
        internal static string WhatWeDoSub {
            get {
                return ResourceManager.GetString("WhatWeDoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy TanZone and have your own tech blog, share tech ideas with your team and other experts..
        /// </summary>
        internal static string WhyAccountC1 {
            get {
                return ResourceManager.GetString("WhyAccountC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy BeautyTeam service, communicate better with your team members and your tasks..
        /// </summary>
        internal static string WhyAccountC2 {
            get {
                return ResourceManager.GetString("WhyAccountC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync your API Studio settings and projects with different devices..
        /// </summary>
        internal static string WhyAccountC3 {
            get {
                return ResourceManager.GetString("WhyAccountC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can you do with an Obisoft account?.
        /// </summary>
        internal static string WhyAccountHeader {
            get {
                return ResourceManager.GetString("WhyAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our work is ourselves.
        /// </summary>
        internal static string WorkIsOurSel {
            get {
                return ResourceManager.GetString("WorkIsOurSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matter enterprise or students, our products must exist one you need..
        /// </summary>
        internal static string WorkSub {
            get {
                return ResourceManager.GetString("WorkSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Account.
        /// </summary>
        internal static string YourEmailAccount {
            get {
                return ResourceManager.GetString("YourEmailAccount", resourceCulture);
            }
        }
    }
}
